`ifndef XYH_DECINFO_V
`define XYH_DECINFO_V

`include "../../top/macros.v"

`define LM75_I2C_ADDR 7'h48
`define LM75_TEMP_REG_PTR 8'h00
`define LM75_TEMP_MSB 8'h14
`define LM75_TEMP_LSB 8'h80

`define XYH_JTAG_RESET_FF_LEVELS 5

`define XYH_STALL_WIDTH  4
`define XYH_STALL_PC     2'd0
`define XYH_STALL_IF     2'd1
`define XYH_STALL_ID     2'd2
`define XYH_STALL_EX     2'd3

`define XYH_INST_MRET    32'h30200073
`define XYH_INST_ECALL   32'h00000073
`define XYH_INST_EBREAK  32'h00100073

`define XYH_DECINFO_GRP_BUS           2:0
`define XYH_DECINFO_GRP_WIDTH         3
`define XYH_DECINFO_GRP_ALU           `XYH_DECINFO_GRP_WIDTH'd1
`define XYH_DECINFO_GRP_BJP           `XYH_DECINFO_GRP_WIDTH'd2
`define XYH_DECINFO_GRP_CSR           `XYH_DECINFO_GRP_WIDTH'd4
`define XYH_DECINFO_GRP_MEM           `XYH_DECINFO_GRP_WIDTH'd5
`define XYH_DECINFO_GRP_SYS           `XYH_DECINFO_GRP_WIDTH'd6
`define XYH_DECINFO_GRP_EXT           `XYH_DECINFO_GRP_WIDTH'd7

`define XYH_DECINFO_ALU_BUS_WIDTH     (`XYH_DECINFO_GRP_WIDTH+14)
`define XYH_DECINFO_ALU_LUI           (`XYH_DECINFO_GRP_WIDTH+0)
`define XYH_DECINFO_ALU_AUIPC         (`XYH_DECINFO_GRP_WIDTH+1)
`define XYH_DECINFO_ALU_ADD           (`XYH_DECINFO_GRP_WIDTH+2)
`define XYH_DECINFO_ALU_SUB           (`XYH_DECINFO_GRP_WIDTH+3)
`define XYH_DECINFO_ALU_SLL           (`XYH_DECINFO_GRP_WIDTH+4)
`define XYH_DECINFO_ALU_SLT           (`XYH_DECINFO_GRP_WIDTH+5)
`define XYH_DECINFO_ALU_SLTU          (`XYH_DECINFO_GRP_WIDTH+6)
`define XYH_DECINFO_ALU_XOR           (`XYH_DECINFO_GRP_WIDTH+7)
`define XYH_DECINFO_ALU_SRL           (`XYH_DECINFO_GRP_WIDTH+8)
`define XYH_DECINFO_ALU_SRA           (`XYH_DECINFO_GRP_WIDTH+9)
`define XYH_DECINFO_ALU_OR            (`XYH_DECINFO_GRP_WIDTH+10)
`define XYH_DECINFO_ALU_AND           (`XYH_DECINFO_GRP_WIDTH+11)
`define XYH_DECINFO_ALU_OP2IMM        (`XYH_DECINFO_GRP_WIDTH+12)
`define XYH_DECINFO_ALU_OP1PC         (`XYH_DECINFO_GRP_WIDTH+13)

`define XYH_DECINFO_BJP_BUS_WIDTH     (`XYH_DECINFO_GRP_WIDTH+8)
`define XYH_DECINFO_BJP_JUMP          (`XYH_DECINFO_GRP_WIDTH+0)
`define XYH_DECINFO_BJP_BEQ           (`XYH_DECINFO_GRP_WIDTH+1)
`define XYH_DECINFO_BJP_BNE           (`XYH_DECINFO_GRP_WIDTH+2)
`define XYH_DECINFO_BJP_BLT           (`XYH_DECINFO_GRP_WIDTH+3)
`define XYH_DECINFO_BJP_BGE           (`XYH_DECINFO_GRP_WIDTH+4)
`define XYH_DECINFO_BJP_BLTU          (`XYH_DECINFO_GRP_WIDTH+5)
`define XYH_DECINFO_BJP_BGEU          (`XYH_DECINFO_GRP_WIDTH+6)
`define XYH_DECINFO_BJP_OP1RS1        (`XYH_DECINFO_GRP_WIDTH+7)

`define XYH_DECINFO_CSR_BUS_WIDTH     (`XYH_DECINFO_GRP_WIDTH+16)
`define XYH_DECINFO_CSR_CSRRW         (`XYH_DECINFO_GRP_WIDTH+0)
`define XYH_DECINFO_CSR_CSRRS         (`XYH_DECINFO_GRP_WIDTH+1)
`define XYH_DECINFO_CSR_CSRRC         (`XYH_DECINFO_GRP_WIDTH+2)
`define XYH_DECINFO_CSR_RS1IMM        (`XYH_DECINFO_GRP_WIDTH+3)
`define XYH_DECINFO_CSR_CSRADDR       `XYH_DECINFO_GRP_WIDTH+4+12-1:`XYH_DECINFO_GRP_WIDTH+4

`define XYH_DECINFO_MEM_BUS_WIDTH     (`XYH_DECINFO_GRP_WIDTH+8)
`define XYH_DECINFO_MEM_LB            (`XYH_DECINFO_GRP_WIDTH+0)
`define XYH_DECINFO_MEM_LH            (`XYH_DECINFO_GRP_WIDTH+1)
`define XYH_DECINFO_MEM_LW            (`XYH_DECINFO_GRP_WIDTH+2)
`define XYH_DECINFO_MEM_LBU           (`XYH_DECINFO_GRP_WIDTH+3)
`define XYH_DECINFO_MEM_LHU           (`XYH_DECINFO_GRP_WIDTH+4)
`define XYH_DECINFO_MEM_SB            (`XYH_DECINFO_GRP_WIDTH+5)
`define XYH_DECINFO_MEM_SH            (`XYH_DECINFO_GRP_WIDTH+6)
`define XYH_DECINFO_MEM_SW            (`XYH_DECINFO_GRP_WIDTH+7)

`define XYH_DECINFO_SYS_BUS_WIDTH     (`XYH_DECINFO_GRP_WIDTH+5)
`define XYH_DECINFO_SYS_ECALL         (`XYH_DECINFO_GRP_WIDTH+0)
`define XYH_DECINFO_SYS_EBREAK        (`XYH_DECINFO_GRP_WIDTH+1)
`define XYH_DECINFO_SYS_NOP           (`XYH_DECINFO_GRP_WIDTH+2)
`define XYH_DECINFO_SYS_MRET          (`XYH_DECINFO_GRP_WIDTH+3)
`define XYH_DECINFO_SYS_FENCE         (`XYH_DECINFO_GRP_WIDTH+4)

`define XYH_DECINFO_EXT_BUS_WIDTH     (`XYH_DECINFO_GRP_WIDTH+3)
`define XYH_DECINFO_EXT_READTEMP      (`XYH_DECINFO_GRP_WIDTH+0)
`define XYH_DECINFO_EXT_SENDID        (`XYH_DECINFO_GRP_WIDTH+1)
`define XYH_DECINFO_EXT_INTFIRE       (`XYH_DECINFO_GRP_WIDTH+2)

`define XYH_DECINFO_WIDTH             `XYH_DECINFO_CSR_BUS_WIDTH

`endif
