+incdir+tb
+incdir+top
+incdir+top/ip
+incdir+top/gpr
+incdir+top/perips
+incdir+top/perips/bridge
+incdir+fpga
top/ip/sage-x_tsmc_cl018g_rvt.v
top/ip/tpd018nv.v
../backend/post_syn_xzr/g03_top_IO.syn.v
fpga/bridge_fpga_wzc.v
fpga/bridge_fpga_xyh.v
fpga/bridge_fpga_hjx.v
fpga/bridge_fpga_xzr.v
fpga/fpga_top.v
utils/gen_ram.v
fpga/rom.v
fpga/ram.v
tb/lm75_model.v
tb/tb_g03_postsyn_backup_probe.v
