 +incdir+tb
 +incdir+top
 +incdir+top/clk_rst
 +incdir+top/ip
 +incdir+top/gpr
 +incdir+top/perips
 +incdir+top/perips/bridge
 +incdir+core00_wzc
 +incdir+core00_wzc/core
 +incdir+core00_wzc/utils
 +incdir+core01_xyh
 +incdir+core01_xyh/core
 +incdir+core01_xyh/utils
 +incdir+core10_hjx
 +incdir+core10_hjx/core
 +incdir+core10_hjx/utils
 +incdir+core11_xzr
 +incdir+core11_xzr/core
 +incdir+core11_xzr/utils
 +incdir+fpga
top/G03_top.v
top/clk_rst/global_clk_sel.v
top/clk_rst/global_rst_ctrl.v
top/ip/icg.v
top/gpr/gpr_top.v
top/gpr/gpr.v
top/perips/perips_top.v
top/perips/rib.v
top/perips/uart.v
top/perips/uart_debug.v
top/perips/pwm.v
top/perips/i2c.v
top/perips/bridge/bridge_wzc.v
top/perips/bridge/bridge_xyh.v
top/perips/bridge/bridge_hjx.v
top/perips/bridge/bridge_xzr.v
core00_wzc/core_wzc.v
core00_wzc/core/exu_alu.v
core00_wzc/core/exu_alu_mux.v
core00_wzc/core/exu_forwarding_unit.v
core00_wzc/core/exu_top.v
core00_wzc/core/global_pipeline_ctrl.v
core00_wzc/core/idu_branch_predictor.v
core00_wzc/core/idu_decoder.v
core00_wzc/core/idu_gpr_mux.v
core00_wzc/core/idu_hazard_detector.v
core00_wzc/core/idu_imm_gen.v
core00_wzc/core/idu_top.v
core00_wzc/core/ifu_ifetch.v
core00_wzc/core/ifu_pc.v
core00_wzc/core/ifu_top.v
core00_wzc/core/kalsit_core.v
core00_wzc/core/mem_ifu.v
core00_wzc/core/mem_lsu.v
core00_wzc/core/mem_rtu.v
core00_wzc/core/mem_sidu.v
core00_wzc/core/mem_top.v
core00_wzc/core/preg_ex_mem.v
core00_wzc/core/preg_id_ex.v
core00_wzc/core/preg_if_id.v
core00_wzc/core/preg_mem_wb.v
core00_wzc/core/wbu_top.v
core00_wzc/utils/full_handshake_rx.v
core00_wzc/utils/full_handshake_tx.v
core00_wzc/utils/gen_buf.v
core00_wzc/utils/gen_dff.v
core00_wzc/utils/gen_ram.v
core00_wzc/utils/vld_rdy.v
core01_xyh/core/core_xyh.v
core01_xyh/core/exu_alu_datapath.v
core01_xyh/core/exu_commit.v
core01_xyh/core/exu_dispatch.v
core01_xyh/core/exu_extension.v
core01_xyh/core/exu_mem.v
core01_xyh/core/exu.v
core01_xyh/core/ext_intfire.v
core01_xyh/core/ext_readtemp.v
core01_xyh/core/ext_sendid.v
core01_xyh/core/idu.v
core01_xyh/core/idu_exu.v
core01_xyh/core/ifu.v
core01_xyh/core/ifu_idu.v
core01_xyh/core/pipe_ctrl.v
core01_xyh/utils/gen_buf.v
core01_xyh/utils/gen_dff.v
core01_xyh/utils/vld_rdy.v
core10_hjx/core/core_hjx.v
core10_hjx/core/exu.v
core10_hjx/core/exu_alu_datapath.v
core10_hjx/core/exu_commit.v
core10_hjx/core/exu_dispatch.v
core10_hjx/core/exu_ext_if.v
core10_hjx/core/exu_ext_rt.v
core10_hjx/core/exu_ext_sid.v
core10_hjx/core/exu_mem.v
core10_hjx/core/idu.v
core10_hjx/core/idu_exu.v
core10_hjx/core/ifu_hjx.v
core10_hjx/core/ifu_idu.v
core10_hjx/core/pipe_ctrl.v
core10_hjx/utils/gen_buf.v
core10_hjx/utils/gen_dff.v
core10_hjx/utils/gen_ram.v
core10_hjx/utils/vld_rdy.v
core11_xzr/core/core_xzr.v
core11_xzr/core/ctrl.v
core11_xzr/core/ex.v
core11_xzr/core/forwarding_unit.v
core11_xzr/core/id.v
core11_xzr/core/id_ex.v
core11_xzr/core/if_id.v
core11_xzr/core/pc_reg.v
core11_xzr/core/regs.v
core11_xzr/utils/gen_buf.v
core11_xzr/utils/gen_dff.v
fpga/bridge_fpga_wzc.v
fpga/bridge_fpga_xyh.v
fpga/bridge_fpga_hjx.v
fpga/bridge_fpga_xzr.v
fpga/fpga_top.v
fpga/rom.v
fpga/ram.v
tb/tb_g03_basic_instr.v
