`timescale 1ns / 1ps

// FPGA integration top for the G03 multi-core SoC.
// chip_sel_vio supplies the active core selection through JTAG/VIO.
module G03_fpga_sys (
    input  wire       clk,
    input  wire       rst_n_i,
    input  wire       debug_en_i,
    output wire       succ,
    output wire       uart_tx_o,
    input  wire       uart_rx_i,
    output wire [2:0] pwm_o,
    inout  wire       i2c_scl,
    inout  wire       i2c_sda
);

    wire [1:0] chip_sel;
    wire [7:0] bridge_soc_to_fpga;
    wire [7:0] bridge_fpga_to_soc;
    wire [1:0] i2c_io_ctrl;
    wire       i2c_scl_i;
    wire       i2c_sda_i;
    wire       debug_rst_n = u_g03_soc.rst_n;
    wire       debug_x27 = u_g03_soc.gpr_x27[0];
    wire       debug_sel_gpr_we = u_g03_soc.core_gpr_we[chip_sel];
    wire [4:0] debug_sel_gpr_waddr = u_g03_soc.core_gpr_waddr[chip_sel];
    wire [31:0] debug_sel_gpr_wdata = u_g03_soc.core_gpr_wdata[chip_sel];
    wire [31:0] debug_sel_if_addr = u_g03_soc.core_if_addr[chip_sel];
    wire [3:0] debug_sel_if_hsk = {
        u_g03_soc.core_if_req_vld[chip_sel], u_g03_soc.core_if_req_rdy[chip_sel],
        u_g03_soc.core_if_rsp_vld[chip_sel], u_g03_soc.core_if_rsp_rdy[chip_sel]
    };
    wire [7:0] debug_uart_state = u_g03_soc.u_perips_top.u_uart_debug.state;
    wire [31:0] debug_uart_write_mem_addr = u_g03_soc.u_perips_top.u_uart_debug.write_mem_addr;
    wire [31:0] debug_uart_write_mem_data = u_g03_soc.u_perips_top.u_uart_debug.write_mem_data;
    wire [1:0] ila_uart_probe = {uart_tx_o, uart_rx_i};
    wire [2:0] ila_ctrl_probe = {rst_n_i, debug_en_i, debug_rst_n};
    wire [37:0] ila_gpr_probe = {debug_sel_gpr_we, debug_sel_gpr_waddr, debug_sel_gpr_wdata};
    wire pwm_float;

    // VIO is generated by Vivado from chip_sel_vio.xci and is controlled over JTAG.
    chip_sel_vio u_chip_sel_vio (
        .clk       (clk),
        .probe_out0(chip_sel)
    );

    g03_soc u_g03_soc (
        .clk                 (clk),
        .rst_n_i             (rst_n_i),
        .debug_en_i          (debug_en_i),
        .chip_sel_i          (chip_sel),
        .succ                (succ),
        .bridge_tx_data_o    (bridge_soc_to_fpga),
        .bridge_rx_data_i    (bridge_fpga_to_soc),
        .uart_tx_o           (uart_tx_o),
        .uart_rx_i           (uart_rx_i),
        .pwm_o               ({pwm_float, pwm_o}),
        .i2c_io_ctrl_o       (i2c_io_ctrl),
        .i2c_scl_i           (i2c_scl_i),
        .i2c_sda_i           (i2c_sda_i)
    );

    fpga_top u_fpga_top (
        .clk                 (clk),
        .rst_n               (rst_n_i),
        .chip_sel_i          (chip_sel),
        .bridge_rx_data_i    (bridge_soc_to_fpga),
        .bridge_tx_data_o    (bridge_fpga_to_soc)
    );

    // fpga_top provides only ROM/RAM bridge storage. Its legacy I2C ports are
    // intentionally left unconnected so it cannot infer a second IOBUF.
    // Keep exactly one explicit bidirectional buffer for each physical I2C line.
    // i2c_io_ctrl=1 releases the open-drain line; IOBUF T=1 is high impedance.
    IOBUF u_i2c_scl_iobuf (
        .I  (1'b0),
        .T  (i2c_io_ctrl[1]),
        .O  (i2c_scl_i),
        .IO (i2c_scl)
    );

    IOBUF u_i2c_sda_iobuf (
        .I  (1'b0),
        .T  (i2c_io_ctrl[0]),
        .O  (i2c_sda_i),
        .IO (i2c_sda)
    );

    ila_0 u_ila_0 (
        .clk    (clk),
        .probe0 (chip_sel),
        .probe1 (ila_uart_probe),
        .probe2 (succ),
        .probe3 (ila_ctrl_probe),
        .probe4 (debug_x27),
        .probe5 (ila_gpr_probe),
        .probe6 (debug_sel_if_addr),
        .probe7 (debug_sel_if_hsk),
        .probe8 (debug_uart_state),
        .probe9 (debug_uart_write_mem_addr),
        .probe10(debug_uart_write_mem_data)
    );

endmodule
