`timescale 1 ns / 1 ps

module tb_uart_debug_packet;

    localparam UART_CTRL_REG   = 32'h30000000;
    localparam UART_STATUS_REG = 32'h30000004;
    localparam UART_BAUD_REG   = 32'h30000008;
    localparam UART_TX_REG     = 32'h3000000c;
    localparam UART_RX_REG     = 32'h30000010;

    // Set this to 1 to send the exact first packet generated by
    // Validation/tinyriscv_fw_downloader.py: filename at byte[1..] and
    // big-endian file size at byte[25..28].
    localparam REAL_DOWNLOADER_FIRST_PACKET = 1'b1;

    reg clk;
    reg rst_n;
    reg debug_en;

    wire req_valid;
    reg  req_ready;
    reg  rsp_valid;
    wire rsp_ready;
    wire mem_we;
    wire[31:0] mem_addr;
    wire[31:0] mem_wdata;
    wire[3:0] mem_sel;
    reg[31:0] mem_rdata;

    reg pending_rsp;
    reg pending_we;
    reg[31:0] pending_addr;
    reg[31:0] pending_wdata;

    reg[7:0] rx_stream[0:255];
    integer rx_len;
    integer rx_idx;

    reg[7:0] pkt[0:34];
    reg[31:0] rom_model[0:15];
    integer rom_write_count;
    integer ack_count;
    integer nak_count;
    integer i;

    always #10 clk = ~clk;

    uart_debug u_uart_debug(
        .clk(clk),
        .rst_n(rst_n),
        .debug_en_i(debug_en),
        .req_valid_o(req_valid),
        .req_ready_i(req_ready),
        .rsp_valid_i(rsp_valid),
        .rsp_ready_o(rsp_ready),
        .mem_we_o(mem_we),
        .mem_addr_o(mem_addr),
        .mem_wdata_o(mem_wdata),
        .mem_sel_o(mem_sel),
        .mem_rdata_i(mem_rdata)
    );

    function[15:0] crc16_step;
        input[15:0] crc_i;
        input[7:0] data_i;
        integer b;
        reg[15:0] crc;
        begin
            crc = crc_i ^ {8'h00, data_i};
            for (b = 0; b < 8; b = b + 1) begin
                if (crc[0]) begin
                    crc = (crc >> 1) ^ 16'ha001;
                end else begin
                    crc = crc >> 1;
                end
            end
            crc16_step = crc;
        end
    endfunction

    task clear_packet;
        integer k;
        begin
            for (k = 0; k < 35; k = k + 1) begin
                pkt[k] = 8'h00;
            end
        end
    endtask

    task append_packet;
        integer k;
        begin
            for (k = 0; k < 35; k = k + 1) begin
                rx_stream[rx_len] = pkt[k];
                rx_len = rx_len + 1;
            end
        end
    endtask

    task put_crc;
        integer k;
        reg[15:0] crc;
        begin
            crc = 16'hffff;
            for (k = 1; k <= 32; k = k + 1) begin
                crc = crc16_step(crc, pkt[k]);
            end
            pkt[33] = crc[7:0];
            pkt[34] = crc[15:8];
        end
    endtask

    task build_first_packet;
        input[31:0] file_size;
        begin
            clear_packet;
            pkt[0] = 8'h00;

            if (REAL_DOWNLOADER_FIRST_PACKET) begin
                // Python downloader format:
                // byte[1..] filename, byte[25..28] big-endian file size.
                pkt[1]  = "f";
                pkt[2]  = "w";
                pkt[3]  = ".";
                pkt[4]  = "b";
                pkt[5]  = "i";
                pkt[6]  = "n";
                pkt[25] = file_size[31:24];
                pkt[26] = file_size[23:16];
                pkt[27] = file_size[15:8];
                pkt[28] = file_size[7:0];
            end else begin
                // Legacy debug-side format: file size at byte[1..4].
                pkt[1] = file_size[31:24];
                pkt[2] = file_size[23:16];
                pkt[3] = file_size[15:8];
                pkt[4] = file_size[7:0];
            end

            put_crc;
            append_packet;
        end
    endtask

    task build_data_packet;
        begin
            clear_packet;
            pkt[0] = 8'h01;

            // This is exactly the byte order produced by convert_data() for
            // three .data words: 00000d13, 00000d93, 0000006f.
            pkt[1]  = 8'h13;
            pkt[2]  = 8'h0d;
            pkt[3]  = 8'h00;
            pkt[4]  = 8'h00;
            pkt[5]  = 8'h93;
            pkt[6]  = 8'h0d;
            pkt[7]  = 8'h00;
            pkt[8]  = 8'h00;
            pkt[9]  = 8'h6f;
            pkt[10] = 8'h00;
            pkt[11] = 8'h00;
            pkt[12] = 8'h00;

            put_crc;
            append_packet;
        end
    endtask

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            req_ready <= 1'b0;
            rsp_valid <= 1'b0;
            mem_rdata <= 32'h0;
            pending_rsp <= 1'b0;
            pending_we <= 1'b0;
            pending_addr <= 32'h0;
            pending_wdata <= 32'h0;
            rx_idx <= 0;
            ack_count <= 0;
            nak_count <= 0;
            rom_write_count <= 0;
            for (i = 0; i < 16; i = i + 1) begin
                rom_model[i] <= 32'h0;
            end
        end else begin
            req_ready <= debug_en;

            if (req_valid && req_ready) begin
                pending_rsp <= 1'b1;
                pending_we <= mem_we;
                pending_addr <= mem_addr;
                pending_wdata <= mem_wdata;
            end

            if (rsp_valid && rsp_ready) begin
                rsp_valid <= 1'b0;
            end

            if (pending_rsp && (!rsp_valid || rsp_ready)) begin
                pending_rsp <= 1'b0;
                rsp_valid <= 1'b1;
                mem_rdata <= 32'h0;

                if (pending_we) begin
                    if (pending_addr[31:28] == 4'h0) begin
                        rom_model[pending_addr[5:2]] <= pending_wdata;
                        rom_write_count <= rom_write_count + 1;
                    end else if (pending_addr == UART_TX_REG) begin
                        if (pending_wdata[7:0] == 8'h06) begin
                            ack_count <= ack_count + 1;
                        end else if (pending_wdata[7:0] == 8'h15) begin
                            nak_count <= nak_count + 1;
                        end
                    end
                end else begin
                    if (pending_addr == UART_STATUS_REG) begin
                        mem_rdata <= (rx_idx < rx_len) ? 32'h2 : 32'h0;
                    end else if (pending_addr == UART_RX_REG) begin
                        mem_rdata <= {24'h0, rx_stream[rx_idx]};
                        rx_idx <= rx_idx + 1;
                    end
                end
            end
        end
    end

    initial begin
        clk = 1'b0;
        rst_n = 1'b0;
        debug_en = 1'b0;
        rx_len = 0;

        build_first_packet(32'd12);
        build_data_packet;

        #100;
        rst_n = 1'b1;
        #100;
        debug_en = 1'b1;

        wait (ack_count == 2);
        #500;

        if (nak_count == 0 &&
            rom_write_count == 8 &&
            rom_model[0] == 32'h00000d13 &&
            rom_model[1] == 32'h00000d93 &&
            rom_model[2] == 32'h0000006f) begin
            $display("UART_DEBUG_PACKET_PASS ack=%0d writes=%0d rom0=%h rom1=%h rom2=%h",
                     ack_count, rom_write_count, rom_model[0], rom_model[1], rom_model[2]);
        end else begin
            $display("UART_DEBUG_PACKET_FAIL ack=%0d nak=%0d writes=%0d rom0=%h rom1=%h rom2=%h",
                     ack_count, nak_count, rom_write_count, rom_model[0], rom_model[1], rom_model[2]);
            $finish;
        end

        $finish;
    end

    initial begin
        #2000000;
        $display("UART_DEBUG_PACKET_TIMEOUT ack=%0d nak=%0d rx_idx=%0d/%0d writes=%0d state=%0d rom0=%h rom1=%h rom2=%h",
                 ack_count, nak_count, rx_idx, rx_len, rom_write_count,
                 u_uart_debug.state, rom_model[0], rom_model[1], rom_model[2]);
        $finish;
    end

endmodule
