`ifndef HJX_DECINFO_V
`define HJX_DECINFO_V

`include "../../top/macros.v"

`define HJX_STALL_WIDTH  4
`define HJX_STALL_PC     2'd0
`define HJX_STALL_IF     2'd1
`define HJX_STALL_ID     2'd2
`define HJX_STALL_EX     2'd3

`define HJX_DECINFO_GRP_BUS           2:0
`define HJX_DECINFO_GRP_WIDTH         3
`define HJX_DECINFO_GRP_ALU           `HJX_DECINFO_GRP_WIDTH'd1
`define HJX_DECINFO_GRP_BJP           `HJX_DECINFO_GRP_WIDTH'd2
`define HJX_DECINFO_GRP_MEM           `HJX_DECINFO_GRP_WIDTH'd5
`define HJX_DECINFO_GRP_SYS           `HJX_DECINFO_GRP_WIDTH'd6
`define HJX_DECINFO_GRP_EXT           `HJX_DECINFO_GRP_WIDTH'd7

`define HJX_DECINFO_ALU_BUS_WIDTH     (`HJX_DECINFO_GRP_WIDTH+14)
`define HJX_DECINFO_ALU_LUI           (`HJX_DECINFO_GRP_WIDTH+0)
`define HJX_DECINFO_ALU_AUIPC         (`HJX_DECINFO_GRP_WIDTH+1)
`define HJX_DECINFO_ALU_ADD           (`HJX_DECINFO_GRP_WIDTH+2)
`define HJX_DECINFO_ALU_SUB           (`HJX_DECINFO_GRP_WIDTH+3)
`define HJX_DECINFO_ALU_SLL           (`HJX_DECINFO_GRP_WIDTH+4)
`define HJX_DECINFO_ALU_SLT           (`HJX_DECINFO_GRP_WIDTH+5)
`define HJX_DECINFO_ALU_SLTU          (`HJX_DECINFO_GRP_WIDTH+6)
`define HJX_DECINFO_ALU_XOR           (`HJX_DECINFO_GRP_WIDTH+7)
`define HJX_DECINFO_ALU_SRL           (`HJX_DECINFO_GRP_WIDTH+8)
`define HJX_DECINFO_ALU_SRA           (`HJX_DECINFO_GRP_WIDTH+9)
`define HJX_DECINFO_ALU_OR            (`HJX_DECINFO_GRP_WIDTH+10)
`define HJX_DECINFO_ALU_AND           (`HJX_DECINFO_GRP_WIDTH+11)
`define HJX_DECINFO_ALU_OP2IMM        (`HJX_DECINFO_GRP_WIDTH+12)
`define HJX_DECINFO_ALU_OP1PC         (`HJX_DECINFO_GRP_WIDTH+13)

`define HJX_DECINFO_BJP_BUS_WIDTH     (`HJX_DECINFO_GRP_WIDTH+8)
`define HJX_DECINFO_BJP_JUMP          (`HJX_DECINFO_GRP_WIDTH+0)
`define HJX_DECINFO_BJP_BEQ           (`HJX_DECINFO_GRP_WIDTH+1)
`define HJX_DECINFO_BJP_BNE           (`HJX_DECINFO_GRP_WIDTH+2)
`define HJX_DECINFO_BJP_BLT           (`HJX_DECINFO_GRP_WIDTH+3)
`define HJX_DECINFO_BJP_BGE           (`HJX_DECINFO_GRP_WIDTH+4)
`define HJX_DECINFO_BJP_BLTU          (`HJX_DECINFO_GRP_WIDTH+5)
`define HJX_DECINFO_BJP_BGEU          (`HJX_DECINFO_GRP_WIDTH+6)
`define HJX_DECINFO_BJP_OP1RS1        (`HJX_DECINFO_GRP_WIDTH+7)

`define HJX_DECINFO_MEM_BUS_WIDTH     (`HJX_DECINFO_GRP_WIDTH+8)
`define HJX_DECINFO_MEM_LB            (`HJX_DECINFO_GRP_WIDTH+0)
`define HJX_DECINFO_MEM_LH            (`HJX_DECINFO_GRP_WIDTH+1)
`define HJX_DECINFO_MEM_LW            (`HJX_DECINFO_GRP_WIDTH+2)
`define HJX_DECINFO_MEM_LBU           (`HJX_DECINFO_GRP_WIDTH+3)
`define HJX_DECINFO_MEM_LHU           (`HJX_DECINFO_GRP_WIDTH+4)
`define HJX_DECINFO_MEM_SB            (`HJX_DECINFO_GRP_WIDTH+5)
`define HJX_DECINFO_MEM_SH            (`HJX_DECINFO_GRP_WIDTH+6)
`define HJX_DECINFO_MEM_SW            (`HJX_DECINFO_GRP_WIDTH+7)

`define HJX_DECINFO_SYS_BUS_WIDTH     (`HJX_DECINFO_GRP_WIDTH+2)
`define HJX_DECINFO_SYS_NOP           (`HJX_DECINFO_GRP_WIDTH+0)
`define HJX_DECINFO_SYS_FENCE         (`HJX_DECINFO_GRP_WIDTH+1)

`define HJX_DECINFO_EXT_BUS_WIDTH     (`HJX_DECINFO_GRP_WIDTH+3)
`define HJX_DECINFO_EXT_SID           (`HJX_DECINFO_GRP_WIDTH+0)
`define HJX_DECINFO_EXT_RT            (`HJX_DECINFO_GRP_WIDTH+1)
`define HJX_DECINFO_EXT_IF            (`HJX_DECINFO_GRP_WIDTH+2)

`define HJX_DECINFO_WIDTH             `HJX_DECINFO_ALU_BUS_WIDTH

`endif
