`timescale 1 ns / 1 ps

`include "../core/defines.v"
`include "../macros.v"

module tb_uart_debug_soc;

    localparam integer UART_BIT_CYCLES = 441;

    reg clk;
    reg rst_n;
    reg uart_rx_pin;
    reg uart_debug_pin;

    wire uart_tx_pin;
    wire[`PWIDTH_O-1:0] bridge_tx;
    wire[`PWIDTH_I-1:0] bridge_rx;

    wire[31:0] x26 = u_soc.u_tinyriscv_core.u_gpr_reg.regs[26];
    wire[31:0] x27 = u_soc.u_tinyriscv_core.u_gpr_reg.regs[27];

    reg[7:0] pkt[0:34];
    integer i;

    always #10 clk = ~clk;

    function[15:0] crc16_step;
        input[15:0] crc_i;
        input[7:0] data_i;
        integer b;
        reg[15:0] crc;
        begin
            crc = crc_i ^ {8'h00, data_i};
            for (b = 0; b < 8; b = b + 1) begin
                if (crc[0]) begin
                    crc = (crc >> 1) ^ 16'ha001;
                end else begin
                    crc = crc >> 1;
                end
            end
            crc16_step = crc;
        end
    endfunction

    task put_crc;
        integer k;
        reg[15:0] crc;
        begin
            crc = 16'hffff;
            for (k = 1; k <= 32; k = k + 1) begin
                crc = crc16_step(crc, pkt[k]);
            end
            pkt[33] = crc[7:0];
            pkt[34] = crc[15:8];
        end
    endtask

    task clear_packet;
        integer k;
        begin
            for (k = 0; k < 35; k = k + 1) begin
                pkt[k] = 8'h00;
            end
        end
    endtask

    task build_first_packet;
        input[31:0] file_size;
        begin
            clear_packet;
            pkt[0] = 8'h00;
            pkt[1] = "f";
            pkt[2] = "w";
            pkt[3] = ".";
            pkt[4] = "b";
            pkt[5] = "i";
            pkt[6] = "n";
            pkt[25] = file_size[31:24];
            pkt[26] = file_size[23:16];
            pkt[27] = file_size[15:8];
            pkt[28] = file_size[7:0];
            put_crc;
        end
    endtask

    task build_data_packet;
        begin
            clear_packet;
            pkt[0] = 8'h01;
            // Bytes generated by tinyriscv_fw_downloader.py convert_data()
            // for words: 00100d13, 00100d93, 0000006f.
            pkt[1]  = 8'h13;
            pkt[2]  = 8'h0d;
            pkt[3]  = 8'h10;
            pkt[4]  = 8'h00;
            pkt[5]  = 8'h93;
            pkt[6]  = 8'h0d;
            pkt[7]  = 8'h10;
            pkt[8]  = 8'h00;
            pkt[9]  = 8'h6f;
            pkt[10] = 8'h00;
            pkt[11] = 8'h00;
            pkt[12] = 8'h00;
            put_crc;
        end
    endtask

    task send_uart_byte;
        input[7:0] data;
        integer b;
        begin
            uart_rx_pin = 1'b0;
            repeat (UART_BIT_CYCLES) @(posedge clk);
            for (b = 0; b < 8; b = b + 1) begin
                uart_rx_pin = data[b];
                repeat (UART_BIT_CYCLES) @(posedge clk);
            end
            uart_rx_pin = 1'b1;
            repeat (UART_BIT_CYCLES) @(posedge clk);
        end
    endtask

    task send_packet;
        integer k;
        begin
            for (k = 0; k < 35; k = k + 1) begin
                send_uart_byte(pkt[k]);
            end
        end
    endtask

    task recv_uart_byte;
        output[7:0] data;
        integer b;
        begin
            data = 8'h00;
            @(negedge uart_tx_pin);
            repeat (UART_BIT_CYCLES + (UART_BIT_CYCLES / 2)) @(posedge clk);
            for (b = 0; b < 8; b = b + 1) begin
                data[b] = uart_tx_pin;
                repeat (UART_BIT_CYCLES) @(posedge clk);
            end
            repeat (UART_BIT_CYCLES) @(posedge clk);
        end
    endtask

    task expect_ack;
        reg[7:0] resp;
        begin
            recv_uart_byte(resp);
            if (resp != 8'h06) begin
                $display("UART_DEBUG_SOC_NAK_OR_BAD_RESP resp=%h", resp);
                $finish;
            end
        end
    endtask

    task send_packet_expect_ack;
        begin
            fork
                send_packet;
                expect_ack;
            join
        end
    endtask

    initial begin
        clk = 1'b0;
        rst_n = 1'b0;
        uart_rx_pin = 1'b1;
        uart_debug_pin = 1'b0;

        #100;
        rst_n = 1'b1;
        #1000;
        uart_debug_pin = 1'b1;

        // Give uart_debug time to initialize UART_CTRL and UART_BAUD through
        // the real RIB slave path before the host starts sending bytes.
        #200000;

        build_first_packet(32'd12);
        send_packet_expect_ack;

        build_data_packet;
        send_packet_expect_ack;

        // Let the bridge finish the final ROM writes.
        #200000;

        if (u_fpga.u_exrom._ram[0] == 32'h00100d13 &&
            u_fpga.u_exrom._ram[1] == 32'h00100d93 &&
            u_fpga.u_exrom._ram[2] == 32'h0000006f) begin
            $display("UART_DEBUG_SOC_PASS rom0=%h rom1=%h rom2=%h rom3=%h bridge_tx=%h bridge_rx=%h",
                     u_fpga.u_exrom._ram[0], u_fpga.u_exrom._ram[1],
                     u_fpga.u_exrom._ram[2], u_fpga.u_exrom._ram[3],
                     bridge_tx, bridge_rx);
        end else begin
            $display("UART_DEBUG_SOC_FAIL rom0=%h rom1=%h rom2=%h rom3=%h state=%0d bridge_tx=%h bridge_rx=%h",
                     u_fpga.u_exrom._ram[0], u_fpga.u_exrom._ram[1],
                     u_fpga.u_exrom._ram[2], u_fpga.u_exrom._ram[3],
                     u_soc.u_uart_debug.state, bridge_tx, bridge_rx);
            $finish;
        end

        // Stop the debug master, reset the pipeline, then execute the
        // downloaded basic-instruction program from ROM[0].
        uart_debug_pin = 1'b0;
        rst_n = 1'b0;
        repeat (10) @(posedge clk);
        rst_n = 1'b1;
        repeat (1000) @(posedge clk);

        if (x26 == 32'd1 && x27 == 32'd1) begin
            $display("UART_DEBUG_SOC_EXEC_PASS x26=%h x27=%h", x26, x27);
        end else begin
            $display("UART_DEBUG_SOC_EXEC_FAIL x26=%h x27=%h", x26, x27);
            $finish;
        end

        $finish;
    end

    initial begin
        #20000000;
        $display("UART_DEBUG_SOC_TIMEOUT rom0=%h rom1=%h rom2=%h state=%0d tx=%b rx=%b bridge_tx=%h bridge_rx=%h",
                 u_fpga.u_exrom._ram[0], u_fpga.u_exrom._ram[1],
                 u_fpga.u_exrom._ram[2], u_soc.u_uart_debug.state,
                 uart_tx_pin, uart_rx_pin, bridge_tx, bridge_rx);
        $finish;
    end

    tinyriscv_soc_top u_soc(
        .clk(clk),
        .rst_ext_i(rst_n),
        .uart_tx_pin(uart_tx_pin),
        .uart_rx_pin(uart_rx_pin),
        .uart_debug_pin(uart_debug_pin),
        .PWM_out_pin(),
        .IIC_SDA_pin(),
        .IIC_SCL_pin(),
        .bridge_tx_o(bridge_tx),
        .bridge_rx_i(bridge_rx)
    );

    FPGA_top u_fpga(
        .clk(clk),
        .rst_n(rst_n),
        .tx_data_i(bridge_tx),
        .rx_data_o(bridge_rx)
    );

endmodule
